### ISSUE TITLE
General issue with Self Signed Certificates

### ISSUE THREAD

**Issue by lupusrex** [e2guardian/e2guardian#100]
Dear all,

to use self signed certificates with e2guardian becomes increasingly difficult:
The current version of Firefox (43.0.4 on OS X 10.11.3) does not establish a connection to Google.com anymore but throws an error "untrusted connection" (Error code: sec_error_unknown_issuer) instead - it is not possible to accept the self signed certificate from e2guardian anymore !

Trusted certificates are available for free now at least from https://letsencrypt.org . 
Would it be possible to use trusted certificates issued by letsencrypt with e2guardian instead of self signed certificates (https://github.com/e2guardian/e2guardian/blob/master/notes/ssl_mitm) ?

Would you please have a look at this issue ? 

Cheers,
Lupus

**Comment by philipianpearce** [comment]
Hi Lupus, 

To do MITM you have to be able to sign a certificate for each site you access, so you have to have access to the private key that generated the rootCA in order to do this. So using a 3rd party to obtain certs is not an option, as far as I know. 

Have you installed your generated root CA on the browser? 

I have just auto-updated to Firefox 44.0 on OSX 10.9.5 and with the root CA we use installed I am not getting any issues in accessing google.com via the latest development version of e2guardian. 

If you are using v3.1.2 then you may have had an issue due to Firefox stopping use of SHA1 encoding in FF v43. However, e2g v3.2 no longer uses SHA1 and due to issues with the number of web sites using SHA1 FF have re-instated support for SHA1 in FF v44. 

Regards 

Philip 
----- Original Message -----

**Comment by lupusrex** [comment]
Hi Philip,

I have updated e2guardian to development version 3.2.0 , FF to v44 and loaded the rootCA into the browser - no issues anymore.

Thanks!
