### ISSUE TITLE
SSLMITM errors

### ISSUE THREAD

**Issue by Kenny690** [e2guardian/e2guardian#150]
Everytime I enable sslmitm I'm having in /var/log/syslog:

Oct 11 13:38:06 Osiris e2guardian[17541]: ssl_read failed
Oct 11 13:38:06 Osiris e2guardian[17541]: error:140780E5:SSL routines:SSL23_READ:ssl handshake failure
Oct 11 13:38:06 Osiris e2guardian[17520]: ssl_read failed
Oct 11 13:38:06 Osiris e2guardian[17520]: error:140780E5:SSL routines:SSL23_READ:ssl handshake failure
Oct 11 13:38:06 Osiris e2guardian[17774]: ssl_read failed
Oct 11 13:38:06 Osiris e2guardian[17774]: error:140780E5:SSL routines:SSL23_READ:ssl handshake failure
Oct 11 13:38:20 Osiris e2guardian[17560]: ssl_write failed
Oct 11 13:38:20 Osiris e2guardian[17560]: error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure
Oct 11 13:38:21 Osiris e2guardian[17644]: ssl_write failed
Oct 11 13:38:21 Osiris e2guardian[17593]: ssl_write failed
Oct 11 13:38:21 Osiris e2guardian[17593]: error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure
Oct 11 13:38:24 Osiris e2guardian[17525]: ssl_write failed
Oct 11 13:38:24 Osiris e2guardian[17525]: error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure
Oct 11 13:38:31 Osiris e2guardian[17593]: ssl_write failed
Oct 11 13:38:31 Osiris e2guardian[17593]: error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure
Oct 11 13:38:31 Osiris e2guardian[17476]: ssl_write failed
Oct 11 13:38:31 Osiris e2guardian[17476]: error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure
Oct 11 13:38:31 Osiris e2guardian[17667]: ssl_write failed
Oct 11 13:38:31 Osiris e2guardian[17667]: error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure
Oct 11 13:38:58 Osiris e2guardian[17555]: ssl_read failed
Oct 11 13:38:58 Osiris e2guardian[17555]: error:140780E5:SSL routines:SSL23_READ:ssl handshake failure
Oct 11 13:39:17 Osiris e2guardian[17597]: ssl_accept failed to client
Oct 11 13:39:17 Osiris e2guardian[17597]: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
Oct 11 13:39:24 Osiris e2guardian[17511]: ssl_accept failed to client
Oct 11 13:39:24 Osiris e2guardian[17511]: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
Oct 11 13:39:27 Osiris e2guardian[17482]: ssl_write failed
Oct 11 13:39:27 Osiris e2guardian[17482]: error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure
Oct 11 13:39:27 Osiris e2guardian[17497]: ssl_write failed
Oct 11 13:39:27 Osiris e2guardian[17497]: error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure
Oct 11 13:39:44 Osiris e2guardian[17573]: ssl_write failed
Oct 11 13:39:55 Osiris e2guardian[17575]: ssl_write failed
Oct 11 13:39:55 Osiris e2guardian[17575]: error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure

Can anyone help me? :C

UPD:
Clients working without any problems. But this errors kinda annoying me. :D

UPD#2:
Actually, there is some freezes on https sites. I did try to change openssl 1.02j to libressl 2.5.0. No difference.

**Comment by Kenny690** [comment]
Finally, I have a great news. I found the problem.
I had this in access.log:
https://195.122.177.141:443 *DENIED* No SSL certificate supplied by server CONNECT 0 0 SSL SITE 2 200 -  All   - -
https://180.87.4.153:443 *DENIED* No SSL certificate supplied by server CONNECT 0 0 SSL SITE 2 200 -  All   - -
https://62.128.100.106:443 *DENIED* No SSL certificate supplied by server CONNECT 0 0 SSL SITE 2 200 -  All   - -
https://62.128.100.43:443 *DENIED* No SSL certificate supplied by server CONNECT 0 0 SSL SITE 2 200 -  All   - -

It's KAV (Kaspersky Antivirus) update centers. Can anyone help me? 
I need to add whole subnet to solve it.

**Comment by eterry1388** [comment]
I'm getting this too.  I have found if you add the domain/ip to `exceptionsiteslist`, the error goes away.  This might have to do with SSL Cert Pinning that is becoming more popular these days, especially in mobile apps.

**Comment by winewood** [comment]
Running at current branch: develop
The good:  MITM is working for every site.  It scans, blocks, and does it's job.  Google redirection is great, and reddit scanning and blocking is perfect!

The Bad:   https://www.youtube.com is blackscreening with error every 2nd video with pauses each commercial many times to black window with unrecoverable error.

Dec 26 19:19:09 ubuntu-minimal e2guardian[8743]: ssl_read failed
Dec 26 19:19:09 ubuntu-minimal e2guardian[8743]: error:140780E5:SSL routines:ssl23_read:ssl handshake failure
Dec 26 19:19:12 ubuntu-minimal e2guardian[9218]: ssl_write failed
Dec 26 19:19:12 ubuntu-minimal e2guardian[9222]: ssl_write failed  <-- appear each youtube ad.

I am not sure how MITM is still working with these errors.   Cert's are being generated, no site is blocked due to them.  Youtube is getting wrecked with annoyances, and is almost unusable.  Firefox, Chrome, it doesn't matter.  Added youtube to nocheckcrtlist and exceptionlist, but these SSL errors apparently originate from the numerous ads outside the youtube domain, and will only impact service during ad insertion.   Is there a work around for an HTTPS site like youtube that requests add content via SSL?  The videos rely on ads in order to play in many cases.

**Comment by fredbcode** [comment]
This is not related with the first issue, please open another ticket or a discussion here https://groups.google.com/forum/#!forum/e2guardian
