### ISSUE TITLE
bannedsslsitelist vs bannedsitelist

### ISSUE THREAD

**Issue by spikedrba** [e2guardian/e2guardian#203]
Hi,

first time I'm implementing ssl filtering, testing on v4. Default config works and I get ssl sites intercepted and banned phrases take effect. However when I tried to ban a site I was surprised by the configuration. Basically I expected that bannedsslsitelist was going to be the place to put ssl sites I wanted to ban. However this turned out not to be correct and I had to put the site in bannedsitelist.

This makes no sense to me. Furthermore the comment at the top of bannedsslsitelist says:

#Unlike the bannedsitelist it overides all other lists so can be used ban an https site white the http is allowed or made an exception

which is again what I'd expected. What am I missing? if I put my site in bannedsslsitelist the site (https) is not banned.

thanks,

Spike

**Comment by fredbcode** [comment]
Hi spike,

I guess you have a problem ssllegacylogic https://github.com/e2guardian/e2guardian/blob/master/configs/e2guardianf1.conf.in#L27 this option is used for users, like me, without SSLMITM

**Comment by spikedrba** [comment]
mmmmh, I'm still confused, bear with me.

First off, the comment below from where you pointed me at says:

_Note that MITM cannot work with this flag set_

so given that I want MITM I should keep it to off, as it is by default.

Second, from the notes/ssl_mitm it says at the bottom:

   Set sslmitm = on in e2guardianfx.conf
   Set ssllegacylogic = off in e2guardianfx.conf

In any case for the sake of texting and to avoid problems with defaults, I uncommented that line and tried with both on and off and in both cases google.com was allowed when specified in bannedsslsites . The only way to stop it, and it actually seems to not matter if ssllegacylogic is on or off, is to put it in bannedsiteslist .

either I'm not understanding something or something is broken (at the very least comments/docs aren't clear, which I'm happy to rectify as soon as I understand it myself and put ssl setup on the wiki).

thanks,

**Comment by fredbcode** [comment]
Yes you are right, there is something strange ssllegacylogic is only related with greylist
There is a bug here or at least a deep change about this, I will contact Philip

**Comment by philipianpearce** [comment]
The logic has not changed in v4.0 on this.

Bannedsslsitelist and localbannedsslsitelist only apply to CONNECT requests when MITM is disabled - they where there so that you could prevent filtering by-pass by going to the https version of a site, and date from before MITM was available.    These lists are ignored when MITM is enabled - If they where not then it would not be possible to white/greylist a sub-url on a site and have the rest of the site banned which is normal e2g behavior.

I have added comments to the e2guardianf1.conf.in file and to the example config files to make this clear.

I know it seems a bit odd - but once the MITM tunnel is opened, e2g just sees the html requests (https is just http over ssl) and so all the standard lists are applied exactly as they would be to a plain http request.  
The only exception to this is exceptionsitelist which is checked before going MITM.  If a https site is in that list, then it is tunneled without going MITM.     All of this is implied in notes/ssl_mitm but maybe not made implicit.   Sorry for any confusion!

**Comment by spikedrba** [comment]
@philipianpearce thanks for the clarification. If I don't hear otherwise I'll go ahead and write up a page on configuring e2g for SSL (largely porting what's now in the notes/ssl_mitm) and trying to clarify the above.
