### ISSUE TITLE
Transparent ssl inteception on 4.x

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#254]
I know that besides bug fixes, you are working on better organized code and conf file calls but is there a way to implement transparent ssl before v5 move?

I ask it because mobile devices ignores wpad configuration and I need a squid in front of e2guardian to do the transparent ssl catch with splice all feature and then forward to e2guardian in a group without MITM.

If it can be done, the only config needed on mobile devices will be the certificate install.

**Comment by forid786** [comment]
I've tried doing this with a simple NAT port forward via pfSense but it broke HTTPS (443), worked fine for HTTP (80).

However, I know it can actually be done because Smoothwall was being used in my college, and on my Android device all I had to do was install the certificate and I was on their proxy for both HTTPS + HTTP. WITHOUT setting up any proxy on the actual phone itself, therefore I'm sure it can be done. Question is how... 

Ideally, with E2Guardian on guest devices I didn't want them to have to setup anything, as the guest group has no MITM. If some kind of redirection was working then no settings would have to be configured client side.

**Comment by philipianpearce** [comment]
I understand the eagerness for transparent https!    However, we are still using largely legacy  code in v4 for the filtering logic.   This code is very complex, unstructured and prone to unwanted side-effects when you add new features.    I estimate that it would take longer to add transparent https successfully to v4, than to complete the code re-structuring and write the transparent https in v5.
The re-structuring work is progressing well and should be completed in a few weeks, at which point I can start looking at starting on the extra features, such as transparent https.
@forid786 - I know how this can be done.  It is just that the legacy code in pre-v5 versions is a very poor vehicle for doing it (it requires a major re-write which is what I am doing in v5). 

Regards Philip

**Comment by forid786** [comment]
@philipianpearce Thanks for the update and clarity. :)

Sorry if I've sounded like I was offending you in my previous post, I just felt that I had to make it clear that it can actually be done. Due to the amount of people that tell me on various forums that it cannot be done. Because I am seeing it being done in real life. 

As you understand fully, transparent HTTPS is incredibly useful for Android devices, and catching devices that haven't properly been able to detect proxy settings via WPAD and as such. Especially in a scenario where you really don't want to hassle your end users to have to mess with settings just to get the Wi-Fi working. I use E2Guardian at home mainly, and it can be a little annoying at times, imagine if you had a pretty large business or organisation? Yeah, it'd get pretty hectic.

I hope everything is going good with the V5, and I will be waiting eagerly. 👍 

PS: I'll take this chance to thank you from the bottom of my heart for carrying on and maintaining E2Guardian, it is exactly what I wanted. A filter that doesn't just rely on useless blacklists, in an age where there's new sites and proxies coming out every second. 
Just know that your work is very useful to society, and perhaps the safe guarding of children and as such, not only that, but it has allowed us to build a community around it. :P  --- (pfSense forums E2 Guardian thread by Marcello)

**Comment by philipianpearce** [comment]
@forid786 Thank you for your kind comments.

Now have transparent https working in test mode in v5develop.

**Comment by marcelloc** [comment]
That's great!

**Comment by justinschw** [comment]
I worry that what I am going to say has been said too many times before, so forgive me, but there is one question I would like to have answered.

First off I was very pleased about discovering e2guardian, more pleased that it is now stable, and particularly pleased that it supports SSL proxying, which dansguardian did not. Back in 2014 I had gone through the trouble of writing my own ICAP content filter in python which was based on dansguardian's file scheme and I was planning on rewriting it in C++ or some other compiled language, when I was relieved to find e2guardian and thought that I could be spared a lot of effort.

However, reading through these new issues reminds me of the frustrations I had with dansguardian in the first place. I have found dansguardian to be the best as far as free content filtering options goes, hands down. I don't know of another open source filter that provides the same degree of functionality. However, what I don't understand is this: I know that it utilizes squid somehow for caching, but what I don't understand is why does it not simply use squid's proxy capabilities itself, and then just act as a content adapter for squid using ecap or icap, instead of implementing its own proxy, which squid already does?

The reason I am saying this is because I have been using squid for the past four years and it already does trasnparent HTTPS proxying very well. It seems like trying to implement this feature into e2guardian is like reinventing the wheel. Why not rewrite dansguardian as an icap service and let squid do all the proxying for you?

**Comment by philipianpearce** [comment]
1. These are not new issues - this issue has been closed for many months. 

2. Please read the site docs, where you will see that v5 e2guardian does support an ICAP server mode, as well as transparent https mode in addition to proxy mode and also has support for direct mode (i.e. not using squid). See https://github.com/e2guardian/e2guardian/releases. 

Note: At Protex we have hundreds of customer deployments of e2g v4 working very successfully with https interception. V5 will just add transparent https and squid-less operation for our customers. The ICAP option is also being intensively tested in an other large deployment. There are pros and cons to either way of working. With v5 you can choose which way you want to go. 

N.B. If I thought I was reinventing the wheel by enabling https interception in e2g, I can assure you that I would not be doing it!! The reasons have been aired well on e2g posts previously and I am not going to repeat them. 

Regards 

Philip 

----- Original Message -----

**Comment by justinschw** [comment]
Wow, that is very good news. Thanks for the info
