### ISSUE TITLE
blacklisted sites blocked, but access.log GET request show *TRUSTED*

### ISSUE THREAD

**Issue by fcoomans** [e2guardian/e2guardian#270]
I am using release 4.1.2.

I created a file site blacklist file /etc/e2guardian/lists/blacklist/domains which contains:
`dl.delivery.mp.microsoft.com`

I then add the file to 
```
# tail -2 /etc/e2guardian/lists/bannedsitelist
.Include</etc/e2guardian/lists/blacklist/domains>
```

When I enter dl.delivery.mp.microsoft.com in the browser, e2guardian blocks it.  I even tried http://3.tlu.dl.delivery.mp.microsoft.com/ and this is also blocked correctly.

The logs show that the GET request is `*TRUSTED*` however:
```
2017.8.18 11:56:27 - 10.148.4.14 http://dl.delivery.mp.microsoft.com/filestreamingservice/files/6
1c14c03-5bbe-448d-b85e-51d0f7b6f175 *TRUSTED* - GET 781 0 - 1 206 - - General - - - - -
2017.8.18 11:56:28 - 10.148.4.14 http://dl.delivery.mp.microsoft.com/filestreamingservice/files/2
d80d100-a9db-4119-923d-496c1d63cc5e *DENIED* Blocked site: dl.delivery.mp.microsoft.com HEAD 0 0
- 1 403 application/octet-stream - General - - - - -
```

Should this not be *DENIED* as well?  Please advise.

**Comment by forid786** [comment]
In my opinion there needs to be some better debugging built in... I am seeing a lot of legit sites being blocked and am excessively using bypass.

**Comment by philipianpearce** [comment]
The lists and configurations supplied with e2guardian are just samples and have been contributed by the community. These were never intended to be used 'as is' - you need to adjust them to your own needs. 

Over blocking is not a 'bug' in e2guardian. Whether something is allowed or not is very subjective, so what may be 'over blocking' to one person may be 'under blocking' to another. It is a configuration issue. E2guardian can be configured to highly block (as in a 'walled garden' type filtering) or to have a very light touch. 

There is sufficient information in the access.log to diagnose the cause of 'over blocking'. If it is a weighted phrase blocking then the words and phrases will be recorded in the log as well as the total score. So change the weighting and or content of the phrases, or increase the naughtiness limit. 
Avoid 'banned phrases' as these are highly likely to produce false positives. Sites that you 'trust' should be made exceptions so that they are not content-checked. At Protex we are constantly using this information in order to adjust our phraselists and url lists in order to provide the right balance for our customers' requirements. 

Also, do not enable foreign language phrase lists, unless you have users that speak them. The same spelt word may be innocent in one language and an unspeakable word in an other. 

It is true that, currently supplied sample phraselists are very dated and, as is, tend to overblock. But to update them needs to be a community effort, I may be able at some point in the future to contribute some updates to the English (UK) phraselists, but other languages can only be updated by those who speak those languages natively. 

Dansguardian had a 'phrasemaster' who took on the role of co-ordinating phrase list changes. Is there anyone in the community who can take this role on for e2guardian? 

Regards 

Philip 

----- Original Message -----

**Comment by philipianpearce** [comment]
If you get odd TRUSTED/DENIED on similar urls - firstly CHECK YOUR LISTS

An url exception will always override a site block.

**Comment by fcoomans** [comment]
This has nothing to do with "over-blocking" or phrase lists.  On the older version 3.5.1, it is blocking and logging both the GET and HEAD correctly:
```
2017.8.21 8:53:23 - 10.148.5.108 http://dl.delivery.mp.microsoft.com/filestreamingservice/files/c89ecb6e-be04-4b5b-867c-d8759956e0d5 *DENIED* Blocked site: dl.delivery.mp.microsoft.com GET 0 0  1 403 application/octet-stream     - -
2017.8.21 8:53:23 - 10.148.5.108 http://dl.delivery.mp.microsoft.com/filestreamingservice/files/7c7916b9-0976-4fcc-be1a-b802e82c4824 *DENIED* Blocked site: dl.delivery.mp.microsoft.com HEAD 0 0  1 403 application/octet-stream     - -
```

Note that both the GET and HEAD is DENIED.

In the new 4.1.2 release it is not logged correctly:
```
2017.8.18 11:56:27 - 10.148.4.14 http://dl.delivery.mp.microsoft.com/filestreamingservice/files/6
1c14c03-5bbe-448d-b85e-51d0f7b6f175 *TRUSTED* - GET 781 0 - 1 206 - - General - - - - -
2017.8.18 11:56:28 - 10.148.4.14 http://dl.delivery.mp.microsoft.com/filestreamingservice/files/2
d80d100-a9db-4119-923d-496c1d63cc5e *DENIED* Blocked site: dl.delivery.mp.microsoft.com HEAD 0 0
- 1 403 application/octet-stream - General - - - - -
```

Note that GET request is incorrectly logged as TRUSTED, yet the HEAD request is DENIED.

I am using the same rules on both builds.  This is clearly a bug in the new release.

**Comment by fredbcode** [comment]
Yes, this is a fix about some bugs, if the requests is not usual like "200 or 304" there is no filtering (but logged as exceptions for security purpose)

This fix issues with identifications (like NTML) and also with fat client (java, citrix, etc) where some requests are needed before the first 200,304, etc

As you see there is a 206 request 

https://github.com/e2guardian/e2guardian/blob/master/src/ConnectionHandler.cpp#L2656

So dl.delivery.mp.microsoft.com is denied with your rules but the first request is allowed as exception.

_If the 206 response is the result of an If-Range request that used a strong cache validator (see section 13.3.3), the response SHOULD NOT include other entity-headers. If the response is the result of an If-Range request that used a weak validator, the response MUST NOT include other entity-headers; this prevents inconsistencies between cached entity-bodies and updated headers. Otherwise, the response MUST include all of the entity-headers that would have been returned with a 200 (OK) response to the same request._

**Comment by philipianpearce** [comment]
@Fredb 

Maybe we should have an option not to log 206's and auth chatter so that logs will be similar to v3? (In v3 206's were not logged). 

Regards 

Philip 

----- Original Message -----

**Comment by fredbcode** [comment]
Yes could be useful, I will take a look

**Comment by fredbcode** [comment]
What do you think about just using logexceptionhits ?

# 0 = never log exceptions
# 1 = log exceptions, but do not explicitly mark them as such
# 2 = always log & mark exceptions (default)

0 and 1 > No log 
2 > Log
