### ISSUE TITLE
Deep URL filtering - google thumbnails

### ISSUE THREAD

**Issue by 1nfrag** [e2guardian/e2guardian#291]
I look after 4 primary schools that run e2guardian. I've been tasked with filtering the google image thumbnails properly as even if listed as a blocked site they are still displayed. So far I've not been able to do this with e2guardian.

Is there any chance of being able to do this in e2guardian or is this just impossible to do since google encrypted their thumbnail links? Hovering above the picture produces the right link address so I thought perhaps someone had a mod that could link the hover above link to the picture and nuke it before it displays...

I did search for this but didnt find anything. Apologies if this has been asked before.

**Comment by 1nfrag** [comment]
The other problem is that google have in there wisdom added new filtering image boxes for image searches.  For instance if we search for “hot girls” in the image search the whole page is banned like it should BUT if we type in “girls” in the search box, it is not banned which is fine but then we can click on the filter box for “hot”, we get image results returned of “hot girls”, this is not okay because it should have been blocked. We are not sure how to stop this behaviour because the results are very similar and one is banned and the other is not, yet both of them should be banned.

**Comment by forid786** [comment]
Hey @1nfrag, are you using MITM? If you are, you should be able to block it just fine. However, you may need to use this in conjunction with Google safe search for maximum results. I've done the same on a similar scenario to yours, forced safe search for all students + had MITM. Blocked most bad content on Google.

**Comment by 1nfrag** [comment]
Hello and thanks for the reply. Yes I do youse MITM. Safe search is enforced but it doesnt block everything we would like. It also as I mention if you block a website and the image originates from that site then it still shows up in the images search result.

**Comment by Dalacor** [comment]
Do you need to use MITM for filtering Google Images? I am using Version 3.4.0.3 and hopefully will upgrade my schools in August to version 5 if I have time.

Ever since Google moved to https in 2013, I have found that Google Searches no longer show in the logs and I also have this issue where you could search for things like penis or whatever and Google Images shows images that are not suitable for a school. We are using Google Safe Search.

Other than blocking google and using kiddle.co I am not sure how to ensure that Google Search does not show inappropriate images.

I am not sure that MITM is practical as (if I have understood it correctly), you have to install a certificate on every pc as well as Ipads etc. I don't know how easy/difficult this will be and whether it can be done on Ipads anyway.

I hope that this issue will get sorted/documented properly as I think the biggest issue is how easy it is to see inappropriate pictures even in Google Safe Search. Kiddle seems to have got this sorted, so I don't know why Google can't do this. Or how to get E2guardian to ban keywords on SSL websites like Google.

**Comment by fredbcode** [comment]
Seem more a configuration issue than a bug, please ask your question to the mailing list
