### ISSUE TITLE
v5develop:enable_ssl, sslmitm

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#327]
I'm using a transparent proxy (via iptables) to e2guardian and then through to squid.  If enablessl=on and sslmitm=on it works good.  With enablessl=on and sslmitm=off, https webpages are returning ERR_CONNECTION_RESET.  

I assume the combination of enablessl=on and sslmitm=off would do three things, correct me if I'm wrong.

1)  Original https certs would be preserved (no mitm certs)
2)  Content (i.e. weightedphraselist, etc) and URL (i.e. bannedurllist) filtering would be off for https (since e2guardian couldn't decrypt traffic, only requests)
3)  Site filter (i.e. bannedsitelist, etc) would still be enabled (since e2guardian could still filter requests)

If I'm wrong, what is the combination of .conf settings that would accomplish all three.

**Comment by philipianpearce** [comment]
enablessl is  a global setting.  It has to be on for any ssl checking or mitm to work.
If enablessl=off all sslmitm and sslcheckcert settings are ignored i.e. they set to off.

sslmitm is a filtergroup setting.   If this is off the effect is the same whether or not enablessl is on or off.

Your three things are correct whenever sslmitm=off.

When sslmitm=on and a site is unavailable e2g will generate a cert for the site so that a splash page can be delivered to the browser, even if the site would not be mitm'ed.    But with sslmitm=off in proxy mode it can return an error to the CONNECT request (which most browsers now interpret as proxy failure) but in transparent mode all that can be done is to drop the connection giving the CONNECTION_RESET.   I.e. Without MITM it is not possible to display a block page for https requests.

I have tested the latest v5develop with these settings and it behaves correctly, with allowed https sites working and blocked ones causing a reset.   

So using site filtering without MITM is not very user friendly.

Even in cases where you do not want to load a Root CA on devices, a better option might be
to have sslmitm=on, put all the https sites you want to allow in the exceptionsitelist (this are not MITM, so original https certs are preserved), and then add a blanket block for all other https sites. The user will then get a cert error for unavailable and blocked sites, if their browser allows they can make an exception and see the block page, or they can be told that is they get a cert error the site is likely blocked.
