### ISSUE TITLE
Bannedregexpurllist not working on https websites

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#408]
If I put in say (friv) to block any friv gaming website, it works on http sites, but not on https sites.
Is there another file that I need to use to block https sites with the word friv in it?

**Comment by fredbcode** [comment]
You mean with sslmitm enabled ?

**Comment by Dalacor** [comment]
No, I don't have SSLmitm enabled. I have come to the conclusion that I need to start using sslmitm as too many websites are not being blocked and search phrases in Google are not being scanned because of lack of sslmitm.

Next week, I will be upgrading E2Guardian from version 3.4.0.3 to Version 5.

I am planning on doing a clean upgrade.

Is there any documentation on whether we still need to use Squid (I understand that IPCap or something was supposed to eliminate this) and exactly what I need to do to get sslmitm to work.

I aim to start this process on Monday. Thank you.

**Comment by philipianpearce** [comment]
See first notes/Upgrading_to_V5, then notes/NEWIN_v4, notes/NEWIN_v5 and notes/ssl_mitm.

See notes/V5_mode_comparison for a table showing features available in explicit proxy, transparent proxy and ICAP server modes.

Squid is no longer required in explicit or transparent proxy mode, unless you are using squid for authentication.  I would recommend that you run caching dns on the same server as e2g.

In ICAP server mode e2g does not talk directly to the clients, but to an ICAP client module in squid or another cache/proxy system.

**Comment by Dalacor** [comment]
Thank you. I will have a look at the V5 notes next week, when I start work on this.

However, I just want to highlight a point that you have made to confirm that I have understood you correctly.

You say that Squid is no longer required unless you are using ICAP as you will need Squid as an ICAP Client? Is that correct?

I will need to review the documentation to understand whether I should go with ICAP or not as I am not bothered about using Squid - had zero issues with Squid other than having to bypass the proxy server completely for windows updates when installing a new laptop. My main aim when upgrading to v5 is to implement MITM really. I have never quite understood what ICAP is supposed to be fixing other than removing the need for Squid.

**Comment by philipianpearce** [comment]
In v2/3/4 you have:- Request client -> e2g -> squid -> site 
Response site -> squid -> e2g -> client 

In V5 you have options:- 

1. In proxy and/or transparent mode with cache 

Request client -> e2g -> squid -> site 
Response site -> squid -> e2g -> client 

2. In proxy and/or transparent mode without cache 

Request client -> e2g -> squid -> site 
Response site -> squid -> e2g -> client 

3. ICAP Server 
Request client -> squid -> site 
|| 
e2g 

Response site -> squid -> client || 
e2g 

Options 1 & 2 are similar to the way previous versions work. 

Option 3 is totally different as users are pointed at squid. 

Option 2 is fastest as e2g handles all the proxying. 

Options 1 & 2 can use all the usual ip/port/dns based authentication methods, e2g has native support for MITM. 

To use proxy pass-through authentication (e.g. ntlm1, basic, digest) option 1 is required as auth is done by back-end squid. 

With option 3 generally user authentication is done in squid and then squid uses ICAP to communicate with e2g in ICAP server mode. Squid passes the request header and user name to e2g which may return a (modified) request to squid to request from the target site or may return a response page (deny etc) which squid sends back to the client. Squid then requests page with the (modified) request header to the target site. When the site responds, squid sends the response to e2g for checking and possible modification before returning it to the client. So generally there are two ICAP requests to e2g for each page requested. In this option no MITM support in e2g but squid-bump may be used. 

With option 1 some of the control is with squid if pass-through auth is used, otherwise most of control and configuration is of e2g and there is a request from client to e2g and then a further one from e2g to squid. 

With option 2 most of the control and configuration is of e2g and there is one single request from client to e2g. 

With option 3 control and configuration is split between squid and e2g, and so is more complex to set up and there are two requests to e2g in addition to the client request to squid. 

So, from your site, I guess you are using port based (and possibly dns based) auth then option 2 is likely to be your best. 

Regards 

Philip 

----- Original Message -----

**Comment by philipianpearce** [comment]
Please disreguard previous post - correct version follows:- 

In v2/3/4 you have:- Request client -> e2g -> squid -> site 
Response site -> squid -> e2g -> client 

In V5 you have options:- 

1. In proxy and/or transparent mode with cache 

Request client -> e2g -> squid -> site 
Response site -> squid -> e2g -> client 

2. In proxy and/or transparent mode without cache 

Request client -> e2g -> site 
Response site -> e2g -> client 

3. ICAP Server 
Request client -> squid -> site 
|| 
e2g 

Response site -> squid -> client || 
e2g 

Options 1 & 2 are similar to the way previous versions work. 

Option 3 is totally different as users are pointed at squid. 

Option 2 is fastest as e2g handles all the proxying. 

Options 1 & 2 can use all the usual ip/port/dns based authentication methods, e2g has native support for MITM. 

To use proxy pass-through authentication (e.g. ntlm1, basic, digest) option 1 is required as auth is done by back-end squid. 

With option 3 generally user authentication is done in squid and then squid uses ICAP to communicate with e2g in ICAP server mode. Squid passes the request header and user name to e2g which may return a (modified) request to squid to request from the target site or may return a response page (deny etc) which squid sends back to the client. Squid then requests page with the (modified) request header to the target site. When the site responds, squid sends the response to e2g for checking and possible modification before returning it to the client. So generally there are two ICAP requests to e2g for each page requested. In this option no MITM support in e2g but squid-bump may be used. 

With option 1 some of the control is with squid if pass-through auth is used, otherwise most of control and configuration is of e2g and there is a request from client to e2g and then a further one from e2g to squid. 

With option 2 most of the control and configuration is of e2g and there is one single request from client to e2g. 

With option 3 control and configuration is split between squid and e2g, and so is more complex to set up and there are two requests to e2g in addition to the client request to squid. 

So, from your site, I guess you are using port based (and possibly dns based) auth then option 2 is likely to be your best. 

Regards 

Philip 

----- Original Message -----

**Comment by Dalacor** [comment]
Thank you. That was very helpful. I will review my sites and see whether we are using much of the caching ability. If not, then I will get rid of Squid as this will mean one less program to install and troubleshoot especially as I know it causes speed issues with Windows Updates and it would make it easier to bypass the proxy for certain websites.

Thank you.

**Comment by prascher** [comment]
Can you please write an explanation of how to setup the different configurations for people coming from v4.

**Comment by philipianpearce** [comment]
See my previous comment is this thread https://github.com/e2guardian/e2guardian/issues/408#issuecomment-405550574

There are notes in all the sample config files on what has been changed from v4. The default set-uo in v5.3 will replicate the default set-up in v4 with the list files in the same paths with the exception of blanket-block options which have moved from list-based to filtergroup storyboard story.fn
