### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#488]
Hi,

I'm permit to open this ticket because E2Guardian seems consume lot of memory.

Here in my syslog:

Dec 20 15:32:34 MyVMkernel: [497806.660728] e2guardian invoked oom-killer: gfp_mask=0x24201ca(GFP_HIGHUSER_MOVABLE|__GFP_COLD), nodemask=0, order=0, oom_score_adj=0
Dec 20 15:32:34 MyVMkernel: [497806.660730] e2guardian cpuset=/ mems_allowed=0
Dec 20 15:32:34 MyVMkernel: [497806.660739] CPU: 4 PID: 12625 Comm: e2guardian Tainted: G           O    4.9.0-8-amd64 #1 Debian 4.9.130-2
Dec 20 15:32:34 MyVMkernel: [497806.660740] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 09/21/2015

[.......]

Dec 20 15:32:34 MyVMkernel: [497806.661173] Out of memory: Kill process 10913 (e2guardian) score 500 or sacrifice child
Dec 20 15:32:34 MyVMkernel: [497806.679485] Killed process 10913 (e2guardian) total-vm:91074944kB, anon-rss:2923988kB, file-rss:0kB, shmem-rss:0kB
Dec 20 15:32:34 MyVMkernel: [497807.312506] oom_reaper: reaped process 10913 (e2guardian), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

In e2guardian logs files, I have nothing at this time or before...

That I constate:
At 2:00 AM, I restart E2guardian.

More the day past, more E2guardian scan webpages, more E2guardian eat RAM.

This day, E2guardian is enter in out of memory.
It seems (maybe I'm wrong), that E2guardian has a memory leak.

Can you tell me how I can enter in debug mode in order to give you more details?

Note: I work on Debian 9 with 6GB of RAM and 2GB of swap. I have about 15 users filtered by E2guardian V 5.2.2.

Best regards
Anthony

**Comment by Anthony-76** [comment]
Hi,

For information this problem appears this day.

For information, I have this message in my dstats.log before the "crash"

1545398714      10000   44      0       0       2695    8       3050    10      216     3
1545399014      10000   51      0       0       2503    8       2793    9       216     3
1545399314      10000   58      0       0       2996    9       3481    11      216     3
1545399614      10000   55      0       0       2427    7       3088    10      216     3
1545399912      10000   61      0       0       1830    6       1909    6       216     3
time            httpw   busy    httpwQ  logQ    conx    conx/s  reqs    reqs/s  maxfd   LCcnt

**Comment by philipianpearce** [comment]
Your httpworkers is far too high for your size system, so from start-up e2g will be consuming far more VM than is available on your systems.  So is not at all surprising that you are getting 'out of memory' after running for a while. Reduce httpworkers to 500, which should be more than enough for 15 users.  Keep looking at dstats and only if you see persistent queuing increase httpworkers a little at a time until queuing stops.   On a system with 6G RAM if you increase httpworkers beyond 1000 you are likely to get memory issues.  
Due to the way the linux kernel allocates memory dynamically, most of the real memory will allocated while e2g is running.  Maximum allocation of real memory is likely to happen when peak load is reached.  Due to the way the kernel allocates memory, the memory usage will then not fall until e2g is re-started.   This is normal with linux programs and does not of itself mean that a memory leak is present.

**Comment by Anthony-76** [comment]
Hi @philipianpearce ,

I understand the mechanism of httpworkers with RAM.
I will reduce the httpworkers value to 500.

So, you can close this ticket.
If the problem still present, I will open new ticket.

Thanks for your explaination :)

Anthony

**Comment by philipianpearce** [comment]
OK I will close this issue.
