### ISSUE TITLE
"http?workers" working to allocate connections dynamically.

### ISSUE THREAD

**Issue by empereira** [e2guardian/e2guardian#522]
Hello,

This is a request for improvement! :D

What is the possibility of e2g working the way it request a connection dynamically allocated? It would be something like what the "xenserver" has in relation to dynamically allocated memory on a vm.

Thank you!

**Comment by philipianpearce** [comment]
I presume that you mean that a httpworker threads be created on demand for a fresh connection.

There is an overhead to creating a new thread, so dynamically starting threads on demand would slow down response times.

When the thread model for e2g was introduced in v4, it was deliberately kept simple for efficiency and ease of maintenance reasons.  This replaced the multi-process (dg) model in previous versions which had dynamic allocation of processes, but which had huge issues with memory overhead and complexity of code for process handling and list updating.   v4/v5 uses much less system memory under similar load than earlier versions.
It might be possible to code a dynamic increase (but not a decrease) in the number of httpthreads, but I can see little value in doing this for a number of reasons.
1) Due to the way the kernel handles memory.  i.e. Once (real) memory is allocated to a process it is never de-allocated until the process stops.  So once peak load is reached, real memory will remain at that level.
2) An idle thread consumes very little real memory or system resources.
3) An upper level of threads would still need to be set to protect against system memory overload.
4) It would make the code more complicated to maintain and likely would work more slowly and consume more memory.
Regards
Philip

**Comment by empereira** [comment]
thanks for your answer @philipianpearce !!!

I have an environment of about 1000 users going through the proxy.

I have a L800 serverU:

Intel(R) Atom(TM) CPU C2758 @ 2.41GHz
8 CPUs: 1 package(s) x 8 core(s)
AES-NI CPU Crypto: Yes (inactive)
16 GB de memória ram

I configured 5000 in Http workers.

My ram memory is around 95% busy when e2g is turned on.

This is normal?

**Comment by philipianpearce** [comment]
It is quite normal for any loaded Linux system to run at 95% total RAM usage as the kernel will use any free memory available to cache disk buffers etc. It will release this if mem is required by an application. 

The lower and more useful figure to look at from 'free' output is the 
'-/+ buffers/cache' line - if the used here is 70% or less then all is OK, and I would think that is fairly typical for a system 
serving a 1000 users. 

Regards 

Philip 

----- Original Message -----
