### ISSUE TITLE
Odroid XU4 gcc compilling error

### ISSUE THREAD

**Issue by antonianis** [e2guardian/e2guardian#526]
Hello, 

I am trying to compile the latest version of e2guardian on Odroid XU4 (Ubuntu Mate 18.04) but I am getting the following errors:

Thread model: posix
gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04)
configure:3312: $? = 0
configure:3301: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:3312: $? = 1
configure:3301: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'; did you mean '--versio                           n'?
g++: fatal error: no input files
compilation terminated.
configure:3312: $? = 1
configure:3332: checking whether the C++ compiler works
configure:3354: g++  -mno-sse2 -g -O2  conftest.cpp  >&5
g++: error: unrecognized command line option '-mno-sse2'; did you mean '-fno-dse                           '?
configure:3358: $? = 1 

Any idea what is the problem? I am not sure if my version of gcc is the problem here. I saw on notes/NEWIN_v5 that gcc v5.4  or later is needed (mine is 7.3.0 and 5.4 is not available on Ubuntu 18.04).

Many thanks in advance.

**Comment by philipianpearce** [comment]
This normally happens when you have not run 'sh autogen.sh' prior to ./configure. 

See https://github.com/e2guardian/e2guardian/blob/2e27a3bf3885d87303e5a1f3f5d939386f81dc94/INSTALL 

Also, please see https://github.com/e2guardian/e2guardian/issues/21 for any future support. 

----- Original Message -----

**Comment by antonianis** [comment]
@philipianpearce thanks for the reply,  but this is not the problem. I have run the autogen.sh and  I have successfully compiled e2guarding on another platform/OS. 

Many thanks.

**Comment by philipianpearce** [comment]
In that case for autogen/configure it will may need someone who is familiar with Odroid XU4 and automake to modify the build files. (Also check that you have the latest automake tools for the platform). 

Otherwise, you could try using (and hand-editing) the src/Makefile from another platform that is similar? 

----- Original Message -----
