### ISSUE TITLE
Google safe search and Youtube Safe search is not working properly. (On Tranparent mode)

### ISSUE THREAD

**Issue by surjitiit** [e2guardian/e2guardian#552]
I'm also facing same problem. Google safe search and Youtube Safe search is not working properly.

when i am using **sslsiteregexplist** file to enable disable google and youtube safe searching. it is not working with or without MITM.

when i am using **urlregexplist** and **addheaderregexplist** file to enable disable google and youtube safe searching. it is not working without MITM. but with MITM it is working fine.

also i want to know if some one have idea about urlregexplist and addheaderregexplist files. When we use these files?

**Comment by philipianpearce** [comment]
sslsiteregexplist is applied to site connections in https - i.e. It internally redirects the SSL connection to the IP of the new site.  This does work.   Note -this list must NOT have urls but only regexs that match site names.

urlregexplist makes changes to url requests. - used to force safesearch and other modes on google etc.
addheaderregexplist - adds headers to requests - used to force restricted search on Youtube
Since these both modify the http headers they can only be actioned with http or with https MITM.

**Comment by surjitiit** [comment]
Thanks for you reply
