### ISSUE TITLE
Setting rqloglocation changes the format of access.log

### ISSUE THREAD

**Issue by opoplawski** [e2guardian/e2guardian#580]
If you enable rqloglocation, it changes the format of access.log by adding the thread id:

https://github.com/e2guardian/e2guardian/commit/23ab2eccc81e4160d64afcab77876f562c13a674#diff-021fa58a54b42c2bd7f32a7b02267782R1486

This breaks parsing of the access.log.  While the thread id is important for the requestlog we really shouldn't be breaking the access.log format.

**Comment by philipianpearce** [comment]
Which logformat are you using? 

This feature is designed for diagnostic use only and the tread_id is required in both request AND access logs so as so be able relate the corresponding entries. When using the default logformat or any of the other tab delimited formats it does not break the parsing of fields, just adds the tread_id to the start of a single field. This was intentional so as not to break log parsing. 

Philip 

----- Original Message -----

**Comment by opoplawski** [comment]
I'm using logfileformat 1 which is space separated.  So I get:
```
YYYY.MM.DD HH:MM:SS - IP.AD.DR.ES URL hw1505: POST 0 0 ....
```
Perhaps the access log message can be duplicated into request.log with the thread id?
