### ISSUE TITLE
v5.4 Reorganize example conf files and list file locations to ease user configuration

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#618]
Reorganize and categorize options in example e2guardian*.conf  config files and list file locations to ease user configuration.  

Put lists relating to a filter group into groupn sub-directory etc.

Add defaults wherever possible to the few options that do not have a default. 

Document presidence of option declaration,  (final entry wins).

This will implement some of the suggestions (not all) from #615 - (work had started on this prior to #615 being posted)

All changes made will be backward compatible with previous v5.4 configuration examples.  No new config options.

This is pure configuration optimization/documentation - no changes to the code relating to the running of e2g as this is largely stable and very near production release.

**Comment by KDGundermann** [comment]
> Reorganize and categorize options in example e2guardian*.conf config files and list file locations to ease user configuration.
> Add defaults wherever possible to the few options that do not have a default.

Hi Philip, 
I have already started to reorganize the options and add some defaults, but on the v5.5 branch..

Shouldn't we start to mark some options as "to be deprecated" in v5.4  and do the actual change in v5.5 ??

**Comment by philipianpearce** [comment]
Hi Klaus, 

The reorganising I am doing is purely to the example .conf file themselves so that they are easier to read and configure for the new user and to the location of the example lists. I am not changing the name of any config options or renaming any internal variables or functions. The only code changes I am making is enable default values where needed. There are only a few of them that need this. In the process I am documenting redundant, depreciated, and ones that will no longer be available in the v5.5 release. 

I do not want to rename conf options without a very good reason (even if how they are implemented internally is different) as this makes supporting multiple versions harder, and where there is a good reason to change (e.g. where an option has an ambiguous name and needs to be clearer) then the next few versions must support both the old and new names. 

So when I have finished we will have a clear view of what code can be safely removed in v5.5 (I have already done some tidying up, but this will will enable a more structured approach.). We can then compare this to your changes to see if any are missing. 

I will make some comments to your comments in #613 which will make clearer the direction I am going with this. 

I have nearly finished revising e2guardian.conf for v5.4. I will send that to you for comment and then start on e2guardianf1.conf. 

Regards 
Philip 

----- Original Message -----

**Comment by KDGundermann** [comment]
Great! And I have done it in code (OptionContainer) group options, which I thought they go logical together and mark those which are not used. So we should have found the same unused options.

**Comment by philipianpearce** [comment]
@KDGundermann   It's taken me longer than I thought to finish this, but attached is the current draft of the reorganized e2guardian.conf.in file.  I will not push it to github until I have completed the exercise on e2guardianf1.conf.in.
[e2guardian_conf_in.txt](https://github.com/e2guardian/e2guardian/files/4988011/e2guardian_conf_in.txt)

**Comment by KDGundermann** [comment]
Hi Philip, 


great work !!


The configuration file is now much easier to understand.


Two annotations:


I would like to see the explanation for __LISTDIR__ 
not at the end of the document in the INFO section,
but where __LISTDIR__ is declared (Line 43)


I would like to declare __LISTDIR__ without trailing backslash.
So instead of:
  .Define LISTDIR <@E2CONFDIR@/lists/>
  sitelist = 'name=nomitm,path=__LISTDIR__common/nomitmsitelist'


I would prefer
  .Define LISTDIR <@E2CONFDIR@/lists>
  sitelist = 'name=nomitm,path=__LISTDIR__/common/nomitmsitelist'


Best regards


Klaus
Original Message processed by david® 
Re: [e2guardian/e2guardian] v5.4 Reorganize example conf files and list file locations to ease user configuration (#618) 28. Juli 2020, 13:36 Uhr 
Von Philip Pearce 
An e2guardian/e2guardian 
Cc (2) Klaus|Mention 


@KDGundermann It's taken me longer than I thought to finish this, but attached is the current draft of the reorganized e2guardian.conf.in file. I will not push it to github until I have completed the exercise on e2guardianf1.conf.in.
e2guardian_conf_in.txt

**Comment by philipianpearce** [comment]
Hi Klaus, 

Thanks for your feedback. 

I'll add a short comment regarding LISTDIR into QUICK_START and refer to the INFO section for more detail. 

I agree that the path would look clearer to read if the the '/' is not added to the end of LISTDIR. 

I will make those changes. 

Regards 
Philip 

----- Original Message -----

**Comment by philipianpearce** [comment]
Initial reorganization completed.    Lists are now in sub-directories of the lists directory with READMEs in the lists and new common and example.group sub-directories.   

e2guardian.conf and e2guardianf1.conf example now in sections with first section QUICK_START 
to aid new users.

**Comment by philipianpearce** [comment]
Pushed to github (v5.4.dev)
