### ISSUE TITLE
E2 + Squid + NTLM + sslreplace

### ISSUE THREAD

**Issue by puppetmaster** [e2guardian/e2guardian#638]
We use E2 5.3.4, with Squid 4.10 on ubuntu 20.04.
Our configuration uses the proxy-ntlm plugin for auth (yes I know it's bad...).

We noticed, youtube and google safesearch were not forced anymore, so we went in a journey to find the cause of this... because it's kind of important.

To clear the air, we tried with the default configuration provided by the project, uncomment somme lines in lists and tested without the proxy-ntlm plugin and it works just fine ! youtube and google are forced to safe mode.

Then we enabled the plugin, and like you imagine ... youtube and google are not safe anymore.

We traced the storyboard with the nice configuration option "storyboardtrace" and in the first case, without proxy-ntlm sslreplace is triggered and everything works fine. 
When we enable the plugin, sslreplace returns just false and nothing appends. We ask for the exact same url "https://www.youtube.com".

I'm out of ideas, and my knowledge of the e2 code is very limited. Is the proxy-ntlm plugin still supported ?

Thanks.

Philippe Caseiro (for EOLE team)

**Comment by fredbcode** [comment]
To be honest, I have not checked the code recently and perhaps there is a bug here.
But for ntlm my advice is using icap mode, and I think that this part of code should be removed from e2

With icap Kerberos/e2 are working now, ntlm is practically deprecated

**Comment by puppetmaster** [comment]
I moved to icap mode, and the result is the same. 
My lists are up to date with the provided exemples from source code but youtube is not forced in safemode when authentication is enabled. I'm still exploring logs to understand what is going on.

Some documentation would be nice.

**Comment by fredbcode** [comment]
Weird, with icap the authentication methods is totally unknown to e2 

Works well with icap off in squid.conf ?

**Comment by puppetmaster** [comment]
If e2guardian is frontal, without auth, it works.
The weirdest is this : 
```
oct. 30 15:18:26 amon e2guardian[1005547]: hw3:  No header recd from client at 127.0.0.1 - errno: 0
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:Entering icap-pre-authcheck line:16 of /etc/e2guardian/preauth.story
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:icap-pre-authcheck returned false
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:Entering icap-checkrequest line:54 of /etc/e2guardian/common.story
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:56 if(connect,) is true
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:Entering icapsslrequestcheck line:220 of /etc/e2guardian/common.story
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:221 if(true,) is true
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:Entering icapsquidbump line:238 of /etc/e2guardian/common.story
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:icapsquidbump returned false
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:resuming: icapsslrequestcheck
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:222 if(true,) is true
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:Entering sslexceptioncheck line:146 of /etc/e2guardian/common.story
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:147 if(sitein,exception) is false
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:148 if(headerin,exceptionheader) is false
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:149 if(useragentin,exceptionuseragent) is false
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:150 if(true,) is true
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:false false
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:sslexceptioncheck returned false
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:resuming: icapsslrequestcheck
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:223 if(true,) is true
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:Entering sslreplace line:115 of /etc/e2guardian/common.story
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:116 if(fullurlin,sslreplace) is true
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB: connect site changed to restrict.youtube.com
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:setconnectsite true
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:sslreplace returned true
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:resuming: icapsslrequestcheck
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:224 if(sitein,banned) is false
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:icapsslrequestcheck returned false
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:resuming: icap-checkrequest
oct. 30 15:18:56 amon e2guardian[1005547]: hw1: SB:icap-checkrequest returned false
oct. 30 15:18:56 amon e2guardian[1005547]: "2020.10.30 15:18:56","-","10.1.2.50","https://restrict.youtube.com:443","*URLMOD* -","CONNECT","0","0","-","1","0","-","10.1.2.50","no_name_group","-","-","-","-","-"
```

And in my browser ... youtube or google are not in safemode at all.

**Comment by fredbcode** [comment]
Hum, maybe I don't understand something, with icap e2guardian can't be in frontal, or there is something wrong in your configuration ?

Only squid must be in frontal, squid is the front and _also _ the out

Example here: 
https://support.olfeo.com/sites/olfeo/files/support/v595/fr/integration_guide/webhelp/Guide_integration/images/Integration_couplage_squid_icap.png 
(from Olfeo)

Squid works alone for connections (in, out), identification, ssl bump, etc

At each state e2 is just requested, eg: An user requests a banned site through Squid with kerberos ID method, in this case e2 is not aware than the identification is kerberos, squid manage identification and the request, like this e2 can just deny the banned domain because squid sends the username and the destination domain, I mean the username - in plain text - with a simple header between squid and e2, X-Authenticated-User (see below icap_send_client_username)


So, if you have a squid with a working identification method in front, this should be working correctly with e2

I personally tested with basic, digest and NTLM (three years ago ok ...) with success and I guess kerberos and others methods should works because with icap identification is not related at all with e2


If squid is in frontal (with ntml) with icap off:

Squid.conf

icap_enable off
icap_service service_req reqmod_precache bypass=0 icap://127.0.0.1:1344/request
icap_service service_resp respmod_precache bypass=0 icap://127.0.0.1:1344/response
adaptation_access service_req allow all
adaptation_access service_resp allow all
icap_send_client_ip on
icap_send_client_username on
adaptation_masterx_shared_names X-ICAP-E2G

youtube and google safesearch are forced ? It works ? And with 
"icap_enable on" not ?

https://github.com/e2guardian/e2guardian/blob/v5.4/notes/icap

**Comment by puppetmaster** [comment]
> Hum, maybe I don't understand something, with icap e2guardian can't be in frontal, or there is something wrong in your configuration ? 

I have tried the two modes, without icap (e2 frontal) with icap squid frontal. So I don't think my configuration is the issue on this part.

With e2 in frontal without icap, the safe mode works, with icap squid frontal, the e2 logs says URLMOD but youtube and google are not in safe mode.

I will try the options of your exemple. Thx

**Comment by fredbcode** [comment]
OK 

Are you using sslbump or sslmitm ?

**Comment by puppetmaster** [comment]
> OK
> 
> Are you using sslbump or sslmitm ?

none, Yes I know ...

**Comment by fredbcode** [comment]
Ah ! So it can't works with icap because e2 can't modify a protected requests

**Comment by puppetmaster** [comment]
Thank you fredbcode, it finaly make sense !

**Comment by fredbcode** [comment]
To be honest I'm surprised that sslreplace works without sslmitm in front :-) 

I will discuss with Philip about that, I'm no longer close to e2guardian project now, so I'm helping just with my poor memory ...

Si j'ai le courage j’installerai une maquette pour tester.

**Comment by fredbcode** [comment]
> We use E2 5.3.4, with Squid 4.10 on ubuntu 20.04.

Can you try the latest 5.4.dev version ? there are a lot of fixes not directly related with NTLM but ...
I have put in place automatic build, here: https://e2guardian.numsys.eu

**Comment by philipianpearce** [comment]
Just to clarify, it is not possible for sslreplace to work when using a pass-though auth method (squid auth behind e2g).
This is why - sslreplace works by changing the CONNECT request to squid (or connect to site in direct mode) and is in the per-group rules.   When using pass-through auth the CONNECT call has to be made earlier to squid in order to determine the user/group. The group is not known until after the CONNECT call has been accepted and so it is too late to modify the target site.   This is really awkward and I agree with Fred that we should now depreciate all of the the proxy-behind auth plugins.  This will also enable much code simplification and improve logic flow.

In v5.4.dev there is a new auth plug-in 'pf-basic' (Proxy First Basic),  which allows you to put squid in front of e2g to do the auth and pass on the username to e2g as the upstream proxy.   This single auth plug-in can be used with any auth supported by squid.

ICAP mode should also work,  I will investigate why it is not, as your trace shows that the sslreplace rule is being met.

V5.4 will be released as the new stable branch within a few weeks and so this is branch I will look at.

Regards
Philip
