### ISSUE TITLE
tail -f /var/log/access.log  lags behind

### ISSUE THREAD

**Issue by KDGundermann** [e2guardian/e2guardian#660]
When you are accessing a web site and want to see which entries are generated in the access.log you will notice that the output in access.log will lag behind.

This is due that linux usually buffers the output written to a file. On ubuntu linux the buffer size is 8k, so only after there were 8k written to the access log, which are about 100 entries, the buffer will be flushed to disk.

I propose to have an option to write to the files in an unbuffered way, so you get an "real time" output when following with 'tail -f'

**Comment by fredbcode** [comment]
Also, HTTPS entries are not logged immediately because there is a lag from server response because of tunneling

Eg: With a proxy as Squid, if you look at access.log you can see immediately lines for all HTTP requests, and wait a little moment for HTTPS, worst there is not a line for each requests because of tunneling

**Comment by KDGundermann** [comment]
Hi Fred, 
yes, there is a delay for HTTPS request, but my pull request is specifically for the delay introduced by the 8k buffer size when writing the log data to a file.

**Comment by philipianpearce** [comment]
Hi, 

The delay in squid for https logging (and for non-MITM https in e2g) is due to browsers holding https connections open for long periods. The entry will be logged only when the connection is closed. 

This was one of the reasons why a request.log is now an option in e2g so that these can be traced if needed. 

Klaus, 

I'm aware of your pull request - It is a good idea - I'll look at it in detail soon. I assume you have implemented it as an option as the buffered mode is best in production (faster and less system calls) for the main log? 

Regards 

Philip 

----- Original Message -----

**Comment by philipianpearce** [comment]
Resolved by switching back to using iostream (as in previous versions).  Sorry for delay in picking this up!
