### ISSUE TITLE
Merging e2guardian back into the DansGuardian codebase

### ISSUE THREAD

**Issue by jasonspiro** [e2guardian/e2guardian#67]
DansGuardian used to be maintained by a team of Smoothwall staff, headed by Philip Allison.  They then handed maintainership over to Aecio F. Neto; but he hasn't made any commits since 2012.

DansGuardian has a variety of amenities associated with it:  a pre-existing userbase, name recognition, a mailing list with a fair number of subscribers, a Wikipedia article about it, and more.

It would be excellent if you could gain co-maintainership and could merge all of your work directly back into the DansGuardian project.  Then you could take advantage of all of its amenities.  Plus, your work would be integrated into the Debian project, so that sysadmins worlwide could use `apt-get dist-upgrade` to gain access to new releases of your work and `reportbug` to submit bug reports.

Are you interested in getting co-maintainership of DansGuardian?

And, if so, have you already requested co-maintainership by opening a ticket in the DansGuardian [bug tracker](//sourceforge.net/p/dansguardian/bugs/) and assigning it to Aecio?

P.S.  Thank you very much for all your hard work on e2guardian.

**Comment by fredbcode** [comment]
I can answer only for myself. 

Previously I worked to DansGuardian, you can see my name in Changelog, I tried to put my modest improvements and fixes into the code. 
I thought (but maybe I was wrong) that I was alone to still support DG, so finally I pushed my new code to my personal website.

But to be honest, I think I have not the skills, and the English practice too, to maintain alone a complex project like DansGuardian.

After a while, I joined Philip who have also made many improvements - better than me - 
For my point of view this is a security, and also there is now a company (E2BN) behind E2guardian, like Smoothwall before, believe me it's better for me and it's better for Dansguardian/E2Guardian. 

Maybe one day I will stop my participation, but now no matter for the project if my poor website is down or my code obsolete ...

About Debian project (and others) I think they will no maintain eternally a dead project, and now the fork is massive our code is very different in many points, and it's worst with the next release in approach.

About E2 I agree that a lack of communication is very costly and we have also some needs (like a great documentation) to be a really great project.

More haste, less speed

PS: But who know, maybe with more volunteers ;)

**Comment by jasonspiro** [comment]
Thank you for your reply.  Let me respond to some of your points.

> But to be honest, I think I have not the skills, and the English practice too, to maintain alone a complex project like DansGuardian.

The more you communicate in English, the better you will get at it. But, if you are concerned about your English skills, then perhaps @philipianpearce could be listed as the official new DansGuardian maintainer instead. Dear Philip: Are you possibly interested in taking over maintainership of DansGuardian?

> there is now a company (E2BN) behind E2guardian, like Smoothwall before, believe me it's better for me and it's better for Dansguardian/E2Guardian

If you merge e2guardian back into the DansGuardian codebase, then perhaps your company could make money by selling and supporting DansGuardian.

> Maybe one day I will stop my participation, but now no matter for the project if my poor website is down or my code obsolete

No matter whether you are working on e2guardian or DansGuardian, you may stop at any time.

If you take maintainership of DansGuardian and later decide to abandon it, then post a message to the mailing list saying:

* That you are abandoning maintainership of the project.
* And that you are abandoning ownership of the mailing list.

Then someone else can contact you — or can contact [SourceForge staff](http://sourceforge.net/blog/when-projects-fade-you-can-revive-them/) and [Yahoo staff](//help.yahoo.com/kb/groups/dealing-inactive-moderators-owners-sln7163.html) — and request maintainership.

> About Debian project (and others) I think they will no maintain eternally a dead project

This is true. If DansGuardian stays dead, then Debian, Fedora, Gentoo, NetBSD, MacPorts, and some of the other DansGuardian downstreams might package e2guardian and might automatically migrate the DansGuardian users over to e2guardian. But some might not. You will make things easier for DansGuardian users if you merge your changes into the DansGuardian codebase.

And there is more that you can gain.

"DansGuardian" is a registered trademark of Daniel Barron. If you get permission:

* You can use the trademark, take over the DansGuardian website, and merge your work into the DansGuardian codebase.
* You can insert ads for your commercial services into the DansGuardian website, Readme file, man page, and documentation.
* You can help prevent DansGuardian users from giving up and switching to another option, such as Untangle [Web Filter Lite](http://www.untangle.com/shop/web-filter-lite) (which is [open source](//gitlab.com/groups/untangle.com)), Barracuda Web Filter, or Smoothwall Secure Web Gateway.

In the end, if you take DansGuardian co-maintainership, you might be able to sell more commercial services and make more money.

> About E2 I agree that a lack of communication is very costly

I do not understand this.  Could you please say it again in French?

P.S. Please note: I am not a DansGuardian maintainer.

**Comment by fredbcode** [comment]
I just mean that I agree about this point, I think a lot of works are needed about E2 reputation, but time have a cost ...

**Comment by frodeseverin** [comment]
I am currently searching for filtering and parental control software for my family, and stumbled across e2guardian via Wikipedia.

I know DansGuardian from way back, I believe it was one of the first solutions of this kind I found for GNU/Linux way back in 1995 or so. So DansGuardian has a lot of inertia and market awareness in and of itself.

One of the sad moments of FLOSS software is when good and prosperous projects like DansGuardian are abandoned. There is always the option of creating a fork, and for a time that may be the best solution. In my opinion, though, the ultimate solution is always to merge back into the original project. At least when the original project is well known and aparently abandoned, and the new maintained fork is less known.

From what I can make out from this GitHub project, development started with a raw copy of the DansGuardian source code on 13 Aug 2013. The latest commit to the DansGuardian source code at 
http://sourceforge.net/p/dansguardian/code/HEAD/tree/
seems to be at 10. September 2012. http://dansguardian.org/ 'Latest News' column has an update concerning downloads from 22 September 2012. There is one more update from 27 May 2015, which is two days ago today, stating that 'All cost for commercial use has been abolished', and signed by Daniel Barron. This at least means he is whatching over his site.

To me theese points put together means that there should be little or no problem in merely merging the e2guardian source files over the existing DansGuardian source files, as the origial has not been modified since the fork started. The matter is then more one of politics than of practicalities.

Surely, I am not a programer. However I'd like to help out in testing the software, and contribute user experiences. I would very much encourage you, @fredbcode and the rest of the programmers of e2guardian to contact Daniel Barron and offer to take maintainership of the DansGuardian project and port over your code there. Perhaps he will even allow the source repository to be moved over here to GitHub?

Hoping for the best for both projects.
;)Frode

**Comment by jasonspiro** [comment]
Agreed.  You don't have to use any of DansGuardian's old infrastructure, such as their SourceForge SVN repository.  If you prefer GitHub, you use GitHub instead.

But it would be good if you would at least take over the DansGuardian name and website.

**Comment by eterry1388** [comment]
:+1: on merging back into DansGuardian and having the code-base here on GitHub.
:-1: on selling this as a product.  It should stay free and opensource.

**Comment by junewinter2013** [comment]
You are not proposing a merge back to Dansguardian, you are proposing a name change from e2guardian back to Dansguardian.

It is a massive WASTE of valuable developers time on non-programming tasks like getting the name of an abandoned project (Dansguardian), they should focus their time on programming.

If you want to give e2guardian more exposure, then don't give it a name change and don't waste developer's time. It is up to users like us (who cannot program well) to support and promote the e2guardian.

Dansguardian is dead, long live e2guardian.
