### ISSUE TITLE
Can't get IP-based filter groups working on v5.4

### ISSUE THREAD

**Issue by takelley1** [e2guardian/e2guardian#700]
```
e2guardian 5.4.4

Built with:  '--enable-sslmitm=yes' '--enable-pcre=yes' '--enable-lfs=yes' '--prefix=/opt/e2guardian' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' 'CXXFLAGS=-march=native -O2
 -pipe'

Linux 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.04.2 LTS
```

I'm having trouble getting filter groups working after updating to v5.4. Currently I'm using IPs to define filter groups.
Here's the steps I took to define my groups:

1. I defined my IP groups in `lists/authplugins/ipgroups`
1. I followed the instructions at the top of `e2guardianf1.conf` and commented out the lines that start with `storyboard =` and `.Define LISTDIR`
1. I copied `e2guardianf1.conf` to `e2guardianf2.conf` and edited it accordingly. 
1. I renamed `examplef1.story` to `group1.story`
1. I added `.Include</opt/e2guardian/etc/e2guardian/preauth.story>` to the top of `group1.story`
1. I copied `group1.story` to `group2.story`

Despite this, all IPs are still being grouped into the default group.
If I run `e2guardian -N`, I receive the following warning:
```
SB warning: Undefined list /opt/e2guardian/etc/e2guardian/group1.story list ipmap used at line 60 of /opt/e2guardian/etc/e2guardian/preauth.story
SB warning: Undefined list /opt/e2guardian/etc/e2guardian/group2.story list ipmap used at line 60 of /opt/e2guardian/etc/e2guardian/preauth.story
```
However, I definitely _have_ defined the correct line in `e2guardian.conf`
```
ipmaplist = 'name=ipmap, path=__LISTDIR__/../authplugins/ipgroups'
```
And the file itself isn't empty:
```
10.0.0.0/255.255.255.0 = filter1
10.0.0.10 = filter2
```

Why does E2Guardian think my `ipmap` list is undefined? What am I doing wrong here? Thank you!

**Comment by philipianpearce** [comment]
preauth.story is used from e2guardian.conf as it is used before the user is assigned to a group, in order to determine the group used. 

The error message you are getting is from the reading of e2guardianf1.conf and group1.story, where you are incorrectly including preauth.story. So e2g was looking for an 'ipmap' in e2guardianf1.conf and failing to find it as it is in e2guardian.conf. Removing this .Include from group1.story (undo your step 5) will stop this error message. 

Also, in your ipgroups file remove the 10.0.0.0/255.255.255.0 line - no need for it as filter1 is the default. 

Please in future use the Google group for support. Github is just for bugs etc. 
See https://github.com/e2guardian/e2guardian/issues/21 

Regards 

Philip 

----- Original Message -----

**Comment by takelley1** [comment]
I've posted in the Google group. Thanks!
