### ISSUE TITLE
[question] variable config

### ISSUE THREAD

**Issue by chifu1234** [e2guardian/e2guardian#703]
Hi Guys!

Quick question I tried to use `.Define` with other Variables then `LISTDIR` is that actually possible?

Example:
`.Define TETSDIR </etc/e2g/test>`

Thanks, Kevin

**Comment by philipianpearce** [comment]
Hi Kevin, 

Currently, .Define can only be used with LISTDIR as this is a hard-coded substitution as file paths are read. 

Just having the one variable was sufficient for the use case (mainly different folders for each filter group while using a common definition file) we were looking at at the time it was implemented. 

But the syntax was designed so that it could be extended to multiple variables. So in some future version (post v5.5) multiple variables may be possible. 

Note that LISTDIR is scoped to the file it is defined in and to any files included after the .Define from that file. Also a .Define LISTDIR can include the currently defined __LISTDIR__ as part of the new LISTDIR. So complex configurations can still be built up by using included files. 

Regards 
Philip 

----- Original Message -----

**Comment by chifu1234** [comment]
super thanks @philipianpearce !

**Comment by chifu1234** [comment]
another thing you can do is to use relative path. it is relative to the current file:
`.Include<../common/nologurllistt>`
