### ISSUE TITLE
problem with persistent connections after CONNECT request which is not an exception in non-MITM mode

### ISSUE THREAD

**Issue by gbouthenot** [e2guardian/e2guardian#760]
Hello.
I am using e2g as a proxy, in direct mode (no squid, e2g is the proxy endpoint).

On some cases, it seems to have problems with (i guess) persistent connection. It usually appears using Chrome / Edge -- When they use Firefox there is no problem anymore.

What make this case complicated is that only a few sites are affected, and not all client computer have the problem. But when they stumble an affected site, it is always buggy on their computer.

I mitigated the problem by reducing the "pcontimeout" from 55 seconds (default) to 5 (minimum allowed) in e2guardian.conf , but the problem is still there. That's why I titled this issue "Problem with persistent connection ?"

Let's say the url "THEURL" is affected.

I can get the first request to THEURL good. But if I refresh, I have to wait for the timeout, and then the request is sent.
If I wait 55 seconds between the requests, it works. But again, I have to wait for a timeout if I refresh the page.

i toggled debug mode for network, and I have a lot of traces, but I don't see what cause this behaviour in the source, maybe the browser assume the connection to the proxy is persistent, but e2g does no listen to it anymore ?

Also when the problem triggers, I have the message "data already in buffer: bufflen: 977 buffstart (some integers) getLine():BaseSocket.cpp:271

I tried e2g v5.5.2 and the latest 5.6.dev branch

**Comment by gbouthenot** [comment]
Debug log is here : https://gist.github.com/gbouthenot/1bb26e5c533462ad38582974f174464a

(I set pconntimeout to 30 seconds)

**Comment by gbouthenot** [comment]
I forgot to say that the site I try to reach is HTTPS. 
I have "enablessl = off " in the configuration file. I don't mitm.

I just found that : If I whitelist the site by putting it in "localexceptionsitelist" or "exceptionsitelist", the problem disappears.

So it may be triggered by filtering. But why Firefox does not have the problem ?

**Comment by philipianpearce** [comment]
Seems that Firefox is closing connection after a CONNECT session is completed and flushing it's SSL buffers, but that Chrome is expecting the proxy to disconnect, and does not flush or close it's SSL session until the connection is closed.  Most host servers shutdown their SSL session properly and disconnect after a connect session, but it looks like you have found some that do not.   I have made a change in a temporary test-v5.5 branch, which I think will fix it (will now behave in the same way as an exceptionsite) so that e2g will close the client connection after all CONNECT sessions.
Please can you test with the test-v5.5 branch to see if it fixes the issue?   I could not test as I do not have a test site to try with!

Philip

**Comment by gbouthenot** [comment]
Thank you. I tested with the test-v5.5 branch, and it appears to work really good. Also web surfing seems much responsible.
Firefox is also faster now, before the patch, some URL took 2 seconds, no they are fetched instantly.
I'll will be pushing the patch in production and see if there is some side effect, in the next few days.
THANK YOU REALLY MUCH !

**Comment by philipianpearce** [comment]
test-v5.5 branch removed and fix applied to v5.5 branch
