### ISSUE TITLE
The problem of function findInList in ListContainer.cpp

### ISSUE THREAD

**Issue by sunshikang4456** [e2guardian/e2guardian#768]
In the function findInList(ListContainer.cpp), the return value of the function is a stack address. When the function returns, this address is an illegal address, and the place where this function is called is equivalent to getting a "wild pointer".

**Comment by philipianpearce** [comment]
Thanks for highlighting this.   I've desk checked the code and yes in certain cases (not all) it is possible that it could return an address that may have been deallocated.   However, we have not seen any issues regarding this on production systems or seen any compiler warnings regarding this, so it may be that the compiler optimizer was picking this up and correcting this in some way. (The issue would have been there from v5.5.0 and possibly earlier).

I'm modifying the findInList and associated functions to return a bool instead of a char* and passing the data back in a String defined by the calling function. This will remove the possibility of memory leaks/illegal pointers and make sure it is thread-safe while still minimizing copying of data.  This is a fairly large code change which would not normally be done in a stable release, but as this it an important fix, I will include it in v5.5.3.
