### ISSUE TITLE
authplugins/ipgroups file not determine some ipblock user group

### ISSUE THREAD

**Issue by szrce** [e2guardian/e2guardian#793]
hi @philipianpearce, i hope you are well,

Can you check the problem below?

in v.5.5.4r

when i write like this ipgrous, will be determine filter1
10.20.20.0/255.255.255.0 = filter3
10.20.20.12 = filter1

but i when i write this like ist working correctly determine filter3

10.20.20.12 = filter3
10.20.20.12 = filter1

actually this list working older version correctly.

**Comment by szrce** [comment]
i did fix like this, its work correctly  ipgroup right now,works sequentially. if are you aviable can you check  @philipianpearce 


```
--- src/ListContainer.cpp.orig	2023-08-21 13:48:27.000000000 +0300
+++ src/ListContainer.cpp	2024-02-05 10:19:03.815278000 +0300
@@ -34,6 +34,7 @@
 
 extern OptionContainer o;
 
+
 // DEFINES
 
 #define ROOTNODESIZE 260
@@ -833,7 +834,7 @@
             }
         }
     }
-    return NULL;
+    return false;
 }
 
 // For phrase lists - grab the text, score and type of a given phrase, based on item number within list
@@ -1619,6 +1620,8 @@
     RegResult Rre;
     String key, value;
 
+    DEBUG_debug("sezerdataipmap"); //read
+
     // split into key & value
     if (line.contains("=")) {
         key = line.before("=");
@@ -1638,16 +1641,18 @@
         //warn = true;
         return;
     }
-
+ 
     // store the IP address (numerically, not as a string) and filter group in either the IP list, subnet list or range list
     if (matchIP.match(key.toCharArray(), Rre)) {
-//        std::cerr << "Is straigth IP " << key << std::endl;
+
+//      std::cerr << "Is straigth IP " << key << std::endl;
         struct in_addr address;
         auto aton_res = inet_aton(key.toCharArray(), &address);
 //        std::cerr << "aton returned " << aton_res << std::endl;
         if (aton_res != 0) {
-            ipmap tmap(ntohl(address.s_addr), value);
+            ipmap tmap(ntohl(address.s_addr), value,1);
             ipmaplist.push_back(tmap);
+    
         }
     } else if (matchSubnet.match(key.toCharArray(), Rre)) {
 //        std::cerr << "Is subnet IP " << key << std::endl;
@@ -1664,7 +1669,6 @@
             ipmaprangelist.push_back(s);
         }
     } else if (matchCIDR.match(key.toCharArray(), Rre)) {
-//        std::cerr << "Is CIDR " << key << std::endl;
         struct in_addr address;
         struct in_addr addressmask;
         String subnet(key.before("/"));
@@ -1696,6 +1700,8 @@
             ipmaprangelist.push_back(r);
         }
     }
+    
+
         // hmmm. the key didn't match any of our regular expressions. output message & return a warning value.
     else {
         E2LOGGER_error( "Entry ", line, " in ", sourcefile, " was not recognised as an IP address, subnet or range");
@@ -1715,7 +1721,19 @@
         return "";
     }
 
-    if (true) {
+    if(true){
+        if(ipmaplist[0].t == 1){
+            for (int i = 0; i <= s; i++) {
+                DEBUG_debug("TEEEEESSS", ipmaplist[i].t, " to debugaaa");
+                if(ipmaplist[i].addr == ip){
+                    DEBUG_debug("sezer straight IP order ", i, " to debugaaa");
+                    return ipmaplist[i].group;
+                }
+            }
+        }
+        return "";
+    }
+    if (false) {
         if (a > s)
             return "";
         int m = (a + s) / 2;
@@ -1750,7 +1768,7 @@
                             auto i = one_above;
                             i--;  // move pointer to record which is the highest value that is less or equal to ip.
                             if ((ip >= i->startaddr) && (ip <= i->endaddr)) {
-                                return i->group;
+                                    return i->group;                                
                             }
                         }
     }
@@ -1798,6 +1816,9 @@
 }
 
 String ListContainer::getIPMapData(std::string &ip) {
+    
+    DEBUG_debug("sezer search look IP ", ip, " to straight IP list");
+
     struct in_addr sin;
     inet_aton(ip.c_str(), &sin);
     uint32_t addr = ntohl(sin.s_addr);

```

```
--- src/ListContainer.hpp.orig	2023-08-21 13:48:27.000000000 +0300
+++ src/ListContainer.hpp	2024-02-05 09:58:42.189983000 +0300
@@ -33,13 +33,23 @@
 class ipmap
 {
 public:
-    ipmap(uint32_t a, String g)
+    ipmap(uint32_t a, String g,int o)
     {
         addr = a;
         group = g;
+
+        if(!initialized_group_order){
+            if(o){
+                initialized_group_order = o;
+                t = o;
+
+            }
+        }
     };
     uint32_t addr;
     String group;
+    int t;
+
     int operator<(const ipmap &a) const
     {
         return addr < a.addr;
@@ -52,6 +62,8 @@
     {
         return a == addr;
     };
+private:
+    int initialized_group_order;
 };
 
 class datamap
```

**Comment by philipianpearce** [comment]
Hi Sezer, 

All iplists are actually two lists internally, an IP List and an IP range list. As with all lists e2g sorts the lists on input into ascending order so the order of the item in the input list has no significance. 

When checking an IP, the sorted IP list is checked first and then if no match is found the sorted range list. This allows individual IPs to have different groups to the general block of addresses. 

So, in your 1st example the entry '10.20.20.12 = filter1' will override the '10.20.20.0/255.255.255.0 filter3' one but all other addresses in the range will be in filter3 group. This is expected behavior. 

In your 2nd example you have a duplicate entry in the IP List for 10.20.20.12. (Duplicate entries should be avoided as it is not clear which is required). 

The library sorting routine will preserve the original order for duplicate keys and search function call will detect a match on the first entry of a duplicate key - however you should not rely on this as the function may be changed in future releases. 

Duplicate matches for single IP and for IP ranges should avoided within an IP map list file. Each file is indexed separately. 

So, if you want a set of entries to override others then you can put the sets of IPmaps into separate files then include them in the main list. The order of <includes> is preserved and the search will return whenever a match is found in an <include> list. 

Regards 
Philip 

----- On 25 Jan, 2024, at 12:06, Sezer Huseyin ***@***.***> wrote: 






hi [ https://github.com/philipianpearce | @philipianpearce ] , i hope you are well, 

Can you check the problem below? 

when i write like this ipgrous, will be determine filter1 
10.20.20.0/255.255.255.0 = filter3 
10.20.20.12 = filter1 

but i when i write this like ist working correctly determine filter3 

10.20.20.12 = filter3 
10.20.20.12 = filter1 

actually this list working older version correctly.

**Comment by szrce** [comment]
Thanks for the information, I did the patch above and it works. This patch returns the filter group if your ipmaplist is first and its IP is in that ipmaplist and looks in the iprangelist if you can't find it.

i will close this issue. 

Thank you for the information and quick response.
