### ISSUE TITLE
Logger build error

### ISSUE THREAD

**Issue by prlw1** [e2guardian/e2guardian#804]
`src/Logger.hpp` essentially does
```
#include <cstdio>

enum class LoggerDestination {
        stdout, stderr
};

int main() {}
```
which results in
```
c++  -O2 -g -Werror -Wall -std=c++11      -c    bug.cc
In file included from /usr/include/g++/cstdio:42,
                 from bug.cc:1:
bug.cc:4:9: error: expected identifier before ‘(’ token
    4 |         stdout, stderr
      |         ^~~~~~
bug.cc:4:9: error: expected ‘}’ before ‘(’ token
bug.cc:3:30: note: to match this ‘{’
    3 | enum class LoggerDestination {
      |                              ^
bug.cc:4:9: error: declaration of ‘__sF’ as array of references
    4 |         stdout, stderr
      |         ^~~~~~
bug.cc:5:1: error: expected initializer before ‘}’ token
    5 | };
      | ^
bug.cc:5:1: error: expected declaration before ‘}’ token
*** Error code 1
````
with gcc, and visual studio is unhappy too.

`<cstdio>` obviously includes `<stdio.h>` which defines
```
#define stdout  (&__sF[1])
#define stderr  (&__sF[2])
```
as macros, so the compiler receives
```
enum class LoggerDestination {
        (&__sF[1]), (&__sF[2])
};
```
which is obviously going to fail.

The problematic lines were introduced in
```
commit edb69efdf44ac986ed913eca2d2d1e1fbcd764d5
Author: klaus <kd.gundermann@zwick-edelstahl.de>
Date:   Tue Jun 30 15:43:06 2020 +0200

    Logger 2nd try
```
which is since the last time I tried to build e2guardian in 2015...

The solution is to simply choose different names than the names of macros. (Or stop using `sprintf` and friends.)

**Comment by prlw1** [comment]
BTW `stdout` and friends are expected to be macros, so this problem shouldn't be system dependent: 
https://en.cppreference.com/w/cpp/io/c/std_streams
which begs the question, "How come it apparently works for you?"

**Comment by philipianpearce** [comment]
@prlw1 Thanks for identifying this issue to being with macro (pre-compliler).  

It sort of makes a nonsense of enum class values being encapsulated and localized!  
 
But makes sense as pre-compiler is just doing text substitution and does not understand the code context.   

Instead of undefining the macros I have changed the labels to upper case as these are only ever used within the Logger class and this leaves the stdio macros intact in case they are used in the future.

"How did it work for me?" (And all the standard builds @fredbcode does on GitHub?) - for the last 3+ years??

The answer is in how stdout and stderr are defined in the "stdio.h" library header.  On my systems (CentOS and ubuntu) it is as follows:

```
/* Standard streams.  */
extern struct _IO_FILE *stdin;		/* Standard input stream.  */
extern struct _IO_FILE *stdout;		/* Standard output stream.  */
extern struct _IO_FILE *stderr;		/* Standard error output stream.  */
#ifdef __STDC__
/* C89/C99 say they're macros.  Make them happy.  */
#define stdin stdin
#define stdout stdout
#define stderr stderr
#endif

```
As the macro for stdout resolves to stdout then the compiler sees the text stdout and compiles OK with the correct label.
Same for stderr.

Regards
Philip

**Comment by fredbcode** [comment]
Hi Philip,
There is an issue now with ci about stdio on Debian

**Comment by philipianpearce** [comment]
> Hi Philip, There is an issue now with ci about stdio on Debian

Yes, there was a bug in 1429e8a - should be fixed in c6144a6 which appears to have passed all checks OK.

**Comment by philipianpearce** [comment]
@prlw1  - is this OK to close now?

**Comment by prlw1** [comment]
Yes, thanks! (Sorry for the delay)

And thanks for the explanation - on my NetBSD system
```
#define stdin   (&__sF[0])
#define stdout  (&__sF[1])
#define stderr  (&__sF[2])
```
so there isn't the extra level of indiriection.
