### ISSUE TITLE
`__CONFFILE` defined twice

### ISSUE THREAD

**Issue by prlw1** [e2guardian/e2guardian#807]
`__CONFFILE` is only used in `src/e2guardian.cpp` which includes `e2config.h` which defines `__CONFFILE`.

However, `src/Makefile.am` also sends `__CONFFILE` through on the command line:
```
e2guardian_CPPFLAGS = -D__CONFFILE='"$(E2CONFFILE)"' \
                        -D__LOGLOCATION='"$(E2LOGLOCATION)/"' \
                        -D__PIDDIR='"$(E2PIDDIR)"' \
                        -D__PROXYUSER='"$(E2PROXYUSER)"' \
                        -D__PROXYGROUP='"$(E2PROXYGROUP)"' \
                        -D__CONFDIR='"$(E2CONFDIR)"' \
                        $(AM_CPPFLAGS)
```
which means I see a multiple definiton warning for every file which includes `e2config.h`.

The solution isn't entirely obvious to me as I think it should be possible with an autotools package to `make PREFIX=somewhere_else install` without needing to do much recompiling, which I think means variables like `sysconfdir` should be left in unexpanded.

**Comment by philipianpearce** [comment]
@prlw1 
I agree, this is confusing - I cannot see the logic for defining most settings in e2config.h and others at compile time.  The only reason I can see is the dansguardian developers wanted to these settings to show on compile. But as e2config.h is regenerated when configure is run I can't see any value in doing this via src/Makefile.am.

For v5.5 I will remove the -D__CONFFILE line from Makefile.am which should fix this issue, and then look at moving all of the defines into e2config.h in the next version, so that we have a more consistent & understandable approach to this.

**Comment by philipianpearce** [comment]
All defines moved to e2config.h in v5.6.dev.
