### ISSUE TITLE
[v5.6.1pre] reintroduces banned phrases not working on youtube.com

### ISSUE THREAD

**Issue by ghost** [e2guardian/e2guardian#822]
It seems that the latest version reintroduces an old bug:

https://groups.google.com/g/e2guardian/c/trw13WxXmRM/

The old solution mentioned in the issue above was to uncomment the line:

`textmimetypes = 'application/xhtml+xml,application/xml,application/json,application/javascript,application/x-javascript'`

But it no longer works in v5.6.1pre.

**Comment by philipianpearce** [comment]
@elyahw  Thanks for the report.   There is an issue with youtube, as described in the groups conversation you reference.

I've checked this behavior on v5.4, v5.5 and v5.6 versions - and it is identical.  So this issue is caused by some change in youtube behavior and is not specific to v5.6.1pre.   The best way to get a filtered result is still to enforce restricted mode.

**Comment by ghost** [comment]
I'm using `v5.4.7r` and filtering on youtube works perfectly fine. It only breaks when I use later versions `5.5` and `5.6`. I am certain it has to do with their configurations.

**Comment by philipianpearce** [comment]
Hi, I've checked the default settings and there has been no change to the relevant list files etc since v5.4.7.

I have also re-checked v5.6.1 and with the following setting changes it seems to be working as described in the groups post.

e2guardian.conf

maxcontentfiltersize = 4096
maxcontentramcachesize = 4096

e2guardianf1.conf

textmimetypes = 'application/json'

And after adding \<block me\> to bannedphraselist I get:

![Screenshot 2024-07-03 at 12 06 03](https://github.com/e2guardian/e2guardian/assets/5214681/993a0ae3-61d8-4b97-8144-ffbaae5006d8)
