### ISSUE TITLE
Possible to have nomitmurllist?

### ISSUE THREAD

**Issue by opoplawski** [e2guardian/e2guardian#826]
Would it be possible to have a nomitmurllist list?

Also, I'm not sure that exceptionurllist is working properly.  If I add:
```
outlook.office365.com/adminapi/
```
to it, it still gets MITM:
```
2024.08.14 13:05:25     -       10.10.20.110    https://outlook.office365.com:443       hw1074: PROXY   CONNECT 0       0   -1       0       -       10.10.20.110            -       -       -       -       -
2024.08.14 13:05:25     -       10.10.20.110    https://outlook.office365.com/adminapi/beta/761303a3-2ec2-424e-8122-be8b689b4996/InvokeCommand       hw1074: MITM_MITM       POST    0       0       -       1       0       -       10.10.20.110        --       -       -       -
```
But if I add `outlook.office365.com` to `exceptionsitelist` or `mitmsitelist` it doesn't.

**Comment by philipianpearce** [comment]
It is not possible to have a nomitmurllist. This is because is it not possible to for e2g to see the http request (including the url) without MITM. 

exceptionurllist will still work as on match the data will not be content-checked but tunneled within the MITM session without any further checks. That is, in exactly the same way as http traffic would have been handled. If you look at the access.log you should see that outlook.office365.com/adminapi is TRUSTED as an exception. 

So what you describe below is expected behavior. 

Regards 
Philip

**Comment by opoplawski** [comment]
Thank you for the explanation.
