### ISSUE TITLE
Weighted phrase carryover?

### ISSUE THREAD

**Issue by matthewl77** [e2guardian/e2guardian#832]
E2guardian seems to be incorrectly detecting weighted phrases in some websites.

This log entry from access.log detects complex weight phrase combinations in an non-existent URL.  There should be no content retrieved and therefore no weighted phrases detected.  You can see the return code is 404, and yet it detected the phrases below.  This is intermittent.  Most of the time it detects nothing in this same url.  Other times it detects other phrases.  It did not seem to be related to any other phrases recorded in the nearby time frame in other URLs.  Several representative log entries at listed below.  Note: I replaced the actual url with "https://non.existent.url"

Actual behavior (intermittent)

"2024.10.26 07:00:25","","192.168.1.166","https://non.existent.url","Content Check limit of 100 : -140 ((- article,  education)+(- article,  social )+- biology +- chemistry +- commerce +- grammar +- interview +- mathematic)","GET","236","-140","","1","404","text/html","192.168.1.166","group1","","","-","-",""

"2024.10.26 07:03:33","","192.168.1.166","https://non.existent.url","Content Check limit of 100 : -15 (- analyse )","GET","236","-15","","1","404","text/html","192.168.1.166","group1","","","-","-",""

Expected behavior:

"2024.10.26 07:00:26","","192.168.1.166","https://non.existent.url","Content Check limit of 100 : 0 ()","GET","236","0","","1","404","text/html","192.168.1.166","group1","","","-","-",""

**Comment by matthewl77** [comment]
I am using e2guardian version 5.5.5 on Linux Mint 20.2, installed from the publicly available DEB file, in transparent MITM proxy mode.

**Comment by philipianpearce** [comment]
Thanks for flagging this up.

Please check the specification of http 404!! 
Servers can return (and commonly DO return) a text/html body to give a user-friendly message to go with the 404. 

E2g can only content-check where there is a content body so if there is no body then you will NOT get a "Content Check limit..." message.    

Your example log entries show a content body size of 236 (This is from the response Content-size header) and a mime type of "text/html".   

I have reviewed the code and the variable that carries the weighted phrase information is local to the checkphrase function and so is created on each call to the function and destroyed when the function completes so it does not look to be a carry-over type issue,  but due to the presence of an actual body within the 404 response.
